import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F4F7FB' },
  header: {
    backgroundColor: '#0E1724',
    paddingHorizontal: 22,
    paddingVertical: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 8,
  },
  headerBrand: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  brandMark: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#0EA5E9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandMarkText: { color: '#FFFFFF', fontWeight: '900', fontSize: 14 },
  brandCopy: { flex: 1 },
  headerTitle: { fontSize: 20, fontWeight: '900', color: '#FFFFFF' },
  headerSubtitle: { fontSize: 13, color: '#9FB0C3', marginTop: 2 },
  logoutButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(239, 68, 68, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.24)',
  },
  logoutText: { color: '#FEE2E2', fontWeight: '900', fontSize: 13 },
  topBar: {
    height: 70,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pageHeading: { fontSize: 16, fontWeight: '900', color: '#0F172A', textTransform: 'capitalize' },
  badgeStatus: {
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#BAE6FD',
  },
  badgeStatusText: { color: '#0369A1', fontSize: 12, fontWeight: '700' },
  sidebar: {
    width: 280,
    backgroundColor: '#07111F',
    padding: 22,
    justifyContent: 'space-between',
    borderRightWidth: 1,
    borderColor: '#11243C',
  },
  sidebarSection: { flex: 1, gap: 8 },
  sidebarItem: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
  },
  sidebarItemActive: {
    backgroundColor: '#0E1724',
    borderLeftWidth: 4,
    borderLeftColor: '#0EA5E9',
  },
  sidebarItemTitle: { color: '#F8FAFC', fontSize: 14, fontWeight: '700' },
  sidebarItemDesc: { color: '#94A3B8', fontSize: 12, marginTop: 4 },
  sidebarProfile: {
    paddingTop: 20,
    borderTopWidth: 1,
    borderColor: '#11243C',
  },
  sidebarUsername: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
  sidebarCompany: { color: '#94A3B8', fontSize: 12, marginTop: 6 },
  sidebarLogout: {
    backgroundColor: '#EF4444',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  sidebarLogoutText: { color: '#FFFFFF', fontWeight: '800' },
  toggleButton: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
  },
  toggleButtonText: { fontSize: 18, fontWeight: '800', color: '#475569' },
  scrollContent: { padding: 24, gap: 20 },
  hero: {
    backgroundColor: '#0F172A',
    borderRadius: 18,
    padding: 24,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'stretch',
    gap: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 10,
  },
  heroCopy: { flex: 1, minWidth: 260 },

  tabsRow: { flexDirection: 'row', gap: 12, flexWrap: 'wrap', marginTop: 6 },
  tabButton: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#334155',
    backgroundColor: 'transparent',
  },
  tabButtonActive: {
    backgroundColor: '#0EA5E9',
    borderColor: '#0EA5E9',
  },
  tabButtonText: { color: '#94A3B8', fontWeight: '700' },
  tabButtonTextActive: { color: '#FFFFFF' },

  statusPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(94, 234, 212, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.22)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    marginBottom: 18,
  },
  statusDot: { width: 8, height: 8, borderRadius: 8, backgroundColor: '#5EEAD4' },
  statusText: { color: '#A7F3D0', fontSize: 12, fontWeight: '900' },
  heroTitle: { color: '#FFFFFF', fontSize: 32, lineHeight: 38, fontWeight: '900', maxWidth: 620 },
  heroText: { color: '#B6C4D5', fontSize: 15, lineHeight: 22, marginTop: 10, maxWidth: 650 },
  heroConsole: {
    minWidth: 230,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 16,
    padding: 18,
    justifyContent: 'center',
  },
  consoleLabel: { color: '#8EA4BC', fontSize: 11, fontWeight: '900' },
  consoleValue: { color: '#5EEAD4', fontSize: 28, fontWeight: '900', marginTop: 8 },
  consoleHint: { color: '#B6C4D5', fontSize: 12, lineHeight: 18, marginTop: 6 },
  metricsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  metricCard: {
    flex: 1,
    minWidth: 160,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E8EDF3',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 6,
  },
  metricLabel: { color: '#64748B', fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  metricValue: { color: '#0F172A', fontSize: 28, fontWeight: '900', marginTop: 8 },
  metricDanger: { color: '#DC2626' },
  metricHint: { color: '#7C8DA0', fontSize: 12, marginTop: 6, fontWeight: '700' },
  workspaceWrap: {
    flexDirection: 'row',
    gap: 24,
    alignItems: 'flex-start',
  },
  formColumn: { flex: 1, minWidth: 320, maxWidth: 420 },
  listColumn: { flex: 2, minWidth: 360 },

  workspace: { flexDirection: 'row', flexWrap: 'wrap', gap: 18, alignItems: 'flex-start' },

  formPanel: {
    flex: 1,
    minWidth: 320,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E8EDF3',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 5,
  },
  listPanel: {
    flex: 2,
    minWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E8EDF3',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 5,
  },
  sectionHeader: { marginBottom: 18 },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 18,
  },
  sectionEyebrow: { color: '#0F766E', fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  sectionTitle: { color: '#0F172A', fontSize: 22, fontWeight: '900', marginTop: 4 },
  sectionSubtitle: { color: '#64748B', fontSize: 13, lineHeight: 20, marginTop: 6 },
  countBadge: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  countBadgeText: { color: '#166534', fontSize: 12, fontWeight: '900' },
  filterRow: { flexDirection: 'row', gap: 12, marginBottom: 16, alignItems: 'center' },
  filterButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filterButtonActive: { backgroundColor: '#0F172A', borderColor: '#0F172A' },
  filterButtonText: { fontSize: 13, fontWeight: '600', color: '#475569' },
  filterButtonTextActive: { color: '#FFFFFF' },
  filterPanel: {
    backgroundColor: '#F8FAFC',
    padding: 14,
    borderRadius: 14,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  sortOption: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
  },
  sortOptionActive: { backgroundColor: '#0F172A', borderColor: '#0F172A' },
  sortOptionText: { fontSize: 12, fontWeight: '700', color: '#475569' },
  sortOptionTextActive: { color: '#FFFFFF' },
  formRow: { flexDirection: 'row', gap: 12 },
  input: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DDE5EF',
    paddingHorizontal: 16,
    paddingVertical: 15,
    marginBottom: 12,
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '700',
  },
  inputHalf: { flex: 1 },
  uploadBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#DDE5EF',
    padding: 16,
    marginBottom: 16,
  },
  uploadTitle: { color: '#0F172A', fontSize: 13, fontWeight: '900' },
  uploadText: { color: '#64748B', fontSize: 12, lineHeight: 18, marginTop: 6 },
  btnSalvar: {
    backgroundColor: '#0EA5E9',
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
  },
  btnSalvarText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },
  loadingState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 54 },
  loadingText: { color: '#64748B', fontSize: 13, fontWeight: '800', marginTop: 12 },
  emptyState: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8EDF3',
    padding: 26,
    alignItems: 'center',
  },
  emptyTitle: { color: '#0F172A', fontSize: 16, fontWeight: '900' },
  emptyText: { color: '#64748B', fontSize: 13, textAlign: 'center', marginTop: 8 },
  sectorTabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 16 },
  sectorTab: {
    borderWidth: 1,
    borderColor: '#DDE5EF',
    backgroundColor: '#F8FAFC',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  sectorTabActive: { backgroundColor: '#0E1724', borderColor: '#0E1724' },
  sectorTabText: { color: '#64748B', fontSize: 12, fontWeight: '900' },
  sectorTabTextActive: { color: '#FFFFFF' },
  sectorBlock: { marginBottom: 20 },
  sectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5EBF2',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  sectorTitle: { color: '#0F172A', fontSize: 15, fontWeight: '900' },
  sectorMeta: { color: '#64748B', fontSize: 12, fontWeight: '800', marginTop: 3 },
  sectorCritical: { color: '#B91C1C', fontSize: 12, fontWeight: '900' },
  productCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5EBF2',
    padding: 16,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 4,
  },
  productCardAlert: { borderColor: '#FCA5A5', backgroundColor: '#FFF3F2' },
  productLeft: { flexDirection: 'row', alignItems: 'center', gap: 14, flex: 1 },
  imageContainer: {
    width: 56,
    height: 56,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#E8EEF6',
  },
  productImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  noImagePlaceholder: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center' },
  noImageText: { color: '#7C8DA0', fontSize: 11, fontWeight: '900' },
  productInfo: { flex: 1 },
  productTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  productName: { color: '#0F172A', fontSize: 15, fontWeight: '900', flex: 1 },
  productMeta: { color: '#64748B', fontSize: 12, marginTop: 6, fontWeight: '700' },
  alertBadge: { backgroundColor: '#FEE2E2', paddingHorizontal: 11, paddingVertical: 6, borderRadius: 999 },
  alertBadgeText: { color: '#B91C1C', fontSize: 11, fontWeight: '900' },
  productStock: { alignItems: 'flex-end', minWidth: 84 },
  stockQty: { color: '#0F172A', fontSize: 22, fontWeight: '900' },
  stockUnit: { color: '#64748B', fontSize: 11, fontWeight: '900', marginTop: 2 },
  detailOverlay: {
    flex: 1,
    backgroundColor: 'rgba(7, 17, 31, 0.62)',
    justifyContent: 'center',
    padding: 20,
  },
  detailPanel: {
    width: '100%',
    maxWidth: 740,
    maxHeight: '92%',
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 12,
  },
  detailHeader: {
    backgroundColor: '#0F172A',
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    borderBottomWidth: 1,
    borderColor: '#172531',
  },
  detailTitle: { color: '#FFFFFF', fontSize: 22, fontWeight: '900', flex: 1 },
  detailSubtitle: { color: '#9FB0C3', fontSize: 13, marginTop: 4, fontWeight: '700' },
  detailClose: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailCloseText: { color: '#FFFFFF', fontSize: 18, fontWeight: '900' },
  detailBody: { padding: 22, gap: 16 },
  detailTop: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  detailImage: {
    width: 160,
    height: 160,
    borderRadius: 16,
    backgroundColor: '#E8EEF6',
    overflow: 'hidden',
  },
  detailImageFill: { width: '100%', height: '100%', resizeMode: 'cover' },
  detailSummary: { flex: 1, minWidth: 260, gap: 12 },
  detailStatus: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  detailStatusAlert: { backgroundColor: '#FEF2F2', borderColor: '#FECACA' },
  detailStatusText: { color: '#166534', fontSize: 12, fontWeight: '900' },
  detailStatusTextAlert: { color: '#B91C1C' },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  detailField: {
    flex: 1,
    minWidth: 150,
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5EBF2',
    padding: 14,
  },
  detailLabel: { color: '#64748B', fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  detailValue: { color: '#0F172A', fontSize: 15, fontWeight: '900', marginTop: 8 },
  rawInfoPanel: { backgroundColor: '#F8FAFC', borderRadius: 16, borderWidth: 1, borderColor: '#E5EBF2', padding: 14 },
  rawInfoTitle: { color: '#0F172A', fontSize: 14, fontWeight: '900', marginBottom: 10 },
  rawInfoRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, paddingVertical: 8 },
  rawInfoKey: { color: '#64748B', fontSize: 12, fontWeight: '800', flex: 1 },
  rawInfoValue: { color: '#0F172A', fontSize: 12, fontWeight: '800', flex: 1, textAlign: 'right' },
});

export default styles;
