import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#EEF3F8' },
  header: {
    backgroundColor: '#07111F',
    paddingHorizontal: 22,
    paddingVertical: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerBrand: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  brandMark: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#5EEAD4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandMarkText: { color: '#07111F', fontWeight: '900', fontSize: 14 },
  brandCopy: { flex: 1 },
  headerTitle: { fontSize: 20, fontWeight: '900', color: '#FFFFFF' },
  headerSubtitle: { fontSize: 13, color: '#9FB0C3', marginTop: 2 },
  logoutButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.25)',
  },
  logoutText: { color: '#FCA5A5', fontWeight: '900', fontSize: 13 },
  scrollContent: { padding: 22, gap: 18 },
  hero: {
    backgroundColor: '#07111F',
    borderRadius: 8,
    padding: 24,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'stretch',
    gap: 18,
  },
  heroCopy: { flex: 1, minWidth: 260 },

  // Tabs do hero
  tabsRow: { flexDirection: 'row', gap: 12, flexWrap: 'wrap', marginTop: 6 },
  tabButton: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#334155',
    backgroundColor: 'transparent',
  },
  tabButtonActive: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  tabButtonText: { color: '#94A3B8', fontWeight: '700' },
  tabButtonTextActive: { color: '#FFFFFF' },

  statusPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(94, 234, 212, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(94, 234, 212, 0.26)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    marginBottom: 16,
  },
  statusDot: { width: 8, height: 8, borderRadius: 8, backgroundColor: '#5EEAD4' },
  statusText: { color: '#A7F3D0', fontSize: 12, fontWeight: '900' },
  heroTitle: { color: '#FFFFFF', fontSize: 30, lineHeight: 36, fontWeight: '900', maxWidth: 620 },
  heroText: { color: '#B6C4D5', fontSize: 15, lineHeight: 22, marginTop: 10, maxWidth: 650 },
  heroConsole: {
    minWidth: 230,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    padding: 18,
    justifyContent: 'center',
  },
  consoleLabel: { color: '#8EA4BC', fontSize: 11, fontWeight: '900' },
  consoleValue: { color: '#5EEAD4', fontSize: 28, fontWeight: '900', marginTop: 8 },
  consoleHint: { color: '#B6C4D5', fontSize: 12, lineHeight: 18, marginTop: 6 },
  metricsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  metricCard: {
    flex: 1,
    minWidth: 160,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 18,
    borderWidth: 1,
    borderColor: '#DDE5EF',
  },
  metricLabel: { color: '#64748B', fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  metricValue: { color: '#0F172A', fontSize: 28, fontWeight: '900', marginTop: 8 },
  metricDanger: { color: '#DC2626' },
  metricHint: { color: '#7C8DA0', fontSize: 12, marginTop: 5, fontWeight: '700' },
  // Layout do painel (mais previsível em telas diferentes)
  workspaceWrap: { 
    flexDirection: 'row', 
    gap: 24, 
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 15,
  },
  formColumn: { flex: 1, minWidth: 320, maxWidth: 420 },
  listColumn: { flex: 2, minWidth: 360 },

  // Mantido por compatibilidade (se algum outro componente usar)
  workspace: { flexDirection: 'row', flexWrap: 'wrap', gap: 18, alignItems: 'flex-start' },

  formPanel: {
    flex: 1,
    minWidth: 320,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 20,
    borderWidth: 1,
    borderColor: '#DDE5EF',
  },
  listPanel: {
    flex: 2,
    minWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 20,
    borderWidth: 1,
    borderColor: '#DDE5EF',
  },
  sectionHeader: { marginBottom: 16 },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 16,
  },
  sectionEyebrow: { color: '#0F766E', fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  sectionTitle: { color: '#0F172A', fontSize: 20, fontWeight: '900', marginTop: 4 },
  sectionSubtitle: { color: '#64748B', fontSize: 13, lineHeight: 19, marginTop: 6 },
  countBadge: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
  },
  countBadgeText: { color: '#166534', fontSize: 12, fontWeight: '900' },
  formRow: { flexDirection: 'row', gap: 10 },
  input: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDE5EF',
    paddingHorizontal: 13,
    paddingVertical: 13,
    marginBottom: 12,
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '700',
  },
  inputHalf: { flex: 1 },
  uploadBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDE5EF',
    padding: 14,
    marginBottom: 14,
  },
  uploadTitle: { color: '#0F172A', fontSize: 13, fontWeight: '900' },
  uploadText: { color: '#64748B', fontSize: 12, lineHeight: 18, marginTop: 5 },
  btnSalvar: {
    backgroundColor: '#5EEAD4',
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  btnSalvarText: { color: '#06111F', fontSize: 14, fontWeight: '900' },
  loadingState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 54 },
  loadingText: { color: '#64748B', fontSize: 13, fontWeight: '800', marginTop: 12 },
  emptyState: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDE5EF',
    padding: 24,
    alignItems: 'center',
  },
  emptyTitle: { color: '#0F172A', fontSize: 16, fontWeight: '900' },
  emptyText: { color: '#64748B', fontSize: 13, textAlign: 'center', marginTop: 6 },
  sectorTabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  sectorTab: {
    borderWidth: 1,
    borderColor: '#DDE5EF',
    backgroundColor: '#F8FAFC',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  sectorTabActive: { backgroundColor: '#07111F', borderColor: '#07111F' },
  sectorTabText: { color: '#64748B', fontSize: 12, fontWeight: '900' },
  sectorTabTextActive: { color: '#FFFFFF' },
  sectorBlock: { marginBottom: 18 },
  sectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5EBF2',
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  sectorTitle: { color: '#0F172A', fontSize: 15, fontWeight: '900' },
  sectorMeta: { color: '#64748B', fontSize: 12, fontWeight: '800', marginTop: 3 },
  sectorCritical: { color: '#B91C1C', fontSize: 12, fontWeight: '900' },
  productCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5EBF2',
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  productCardAlert: { borderColor: '#FCA5A5', backgroundColor: '#FFF7F7' },
  productLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  imageContainer: {
    width: 54,
    height: 54,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#E8EEF6',
  },
  productImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  noImagePlaceholder: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center' },
  noImageText: { color: '#7C8DA0', fontSize: 11, fontWeight: '900' },
  productInfo: { flex: 1 },
  productTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  productName: { color: '#0F172A', fontSize: 15, fontWeight: '900', flex: 1 },
  productMeta: { color: '#64748B', fontSize: 12, marginTop: 6, fontWeight: '700' },
  alertBadge: { backgroundColor: '#FEE2E2', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 999 },
  alertBadgeText: { color: '#B91C1C', fontSize: 11, fontWeight: '900' },
  productStock: { alignItems: 'flex-end', minWidth: 74 },
  stockQty: { color: '#0F172A', fontSize: 22, fontWeight: '900' },
  stockUnit: { color: '#64748B', fontSize: 11, fontWeight: '900', marginTop: 2 },
  detailOverlay: {
    flex: 1,
    backgroundColor: 'rgba(7, 17, 31, 0.62)',
    justifyContent: 'center',
    padding: 18,
  },
  detailPanel: {
    width: '100%',
    maxWidth: 720,
    maxHeight: '92%',
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    overflow: 'hidden',
  },
  detailHeader: {
    backgroundColor: '#07111F',
    padding: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  detailTitle: { color: '#FFFFFF', fontSize: 22, fontWeight: '900', flex: 1 },
  detailSubtitle: { color: '#9FB0C3', fontSize: 13, marginTop: 4, fontWeight: '700' },
  detailClose: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailCloseText: { color: '#FFFFFF', fontSize: 18, fontWeight: '900' },
  detailBody: { padding: 18, gap: 14 },
  detailTop: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  detailImage: {
    width: 150,
    height: 150,
    borderRadius: 8,
    backgroundColor: '#E8EEF6',
    overflow: 'hidden',
  },
  detailImageFill: { width: '100%', height: '100%', resizeMode: 'cover' },
  detailSummary: { flex: 1, minWidth: 240, gap: 10 },
  detailStatus: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  detailStatusAlert: { backgroundColor: '#FEF2F2', borderColor: '#FCA5A5' },
  detailStatusText: { color: '#166534', fontSize: 12, fontWeight: '900' },
  detailStatusTextAlert: { color: '#B91C1C' },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  detailField: {
    flex: 1,
    minWidth: 150,
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5EBF2',
    padding: 12,
  },
  detailLabel: { color: '#64748B', fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  detailValue: { color: '#0F172A', fontSize: 15, fontWeight: '900', marginTop: 6 },
  rawInfoPanel: { backgroundColor: '#F8FAFC', borderRadius: 8, borderWidth: 1, borderColor: '#E5EBF2', padding: 12 },
  rawInfoTitle: { color: '#0F172A', fontSize: 14, fontWeight: '900', marginBottom: 8 },
  rawInfoRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, paddingVertical: 7 },
  rawInfoKey: { color: '#64748B', fontSize: 12, fontWeight: '800', flex: 1 },
  rawInfoValue: { color: '#0F172A', fontSize: 12, fontWeight: '800', flex: 1, textAlign: 'right' },
});

export default styles;
